name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Déployer le frontend (React)
      - name: Build Docker image for frontend
        run: |
          docker build  -t mon-frontend ./frontend .
      
      - name: Deploy frontend container
        run: |
          docker stop myapp-frontend || true
          docker rm myapp-frontend || true
          docker run -d -p 5173:5173 --name myapp-frontend mon-frontend

      # Déployer le backend (Express)
      - name: Build Docker image for backend
        run: |
          docker build  -t mon-backend .
      
      - name: Deploy backend container
        run: |
          docker stop myapp-backend || true
          docker rm myapp-backend || true
          docker run -d -p 5000:5000 --name myapp-backend mon-backend
